language: php
sudo: required
dist: trusty
group: edge


matrix:
  include:
    - php: 7.1
      env:
        - SEND_COVERAGE=true
        - CS_FIX=true
    - php: 7.2
    - php: 7.3
    - php: nightly
  allow_failures:
    - php: nightly

addons:
  apt:
    packages:
      - language-pack-fr

env:
    global:
        - SEND_COVERAGE=false
        - CS_FIX=false

before_script:
  - mkdir -p tests/logs
  - mkdir -p tests/tmp/cache 
  - mkdir -p build/logs
  - mysql -e "DROP DATABASE IF EXISTS phpunit_soluble_schema_db;" -u root
  - mysql -e "CREATE DATABASE phpunit_soluble_schema_db;" -u root
  - zcat tests/data/mysql/schema.sql.gz | mysql -u root phpunit_soluble_schema_db
  - zcat tests/data/mysql/data.sql.gz | mysql -u root phpunit_soluble_schema_db
  - mysql -e "SHOW DATABASES;" -u root
  - mysql -e "CONNECT phpunit_soluble_schema_db; SHOW TABLES;" -u root  
  - composer self-update
  - composer install
script: 
  - ./vendor/bin/phpunit -v
  - if [[ $CS_FIX == true ]]; then ./vendor/bin/php-cs-fixer --diff --dry-run -v fix; fi

after_script:
  - if [[ $SEND_COVERAGE == true ]]; then wget https://scrutinizer-ci.com/ocular.phar; fi
  - if [[ $SEND_COVERAGE == true ]]; then php ocular.phar code-coverage:upload --format=php-clover tests/build/logs/clover.xml; fi
