<?php

/*
 * soluble-flexstore library
 *
 * @author    Vanvelthem Sébastien
 * @link      https://github.com/belgattitude/soluble-flexstore
 * @copyright Copyright (c) 2016-2017 Vanvelthem Sébastien
 * @license   MIT License https://github.com/belgattitude/soluble-flexstore/blob/master/LICENSE.md
 *
 */

namespace SolubleTest\FlexStore\ResultSet;

use Soluble\FlexStore\ResultSet\ResultSet;
use Soluble\FlexStore\FlexStore;
use Soluble\FlexStore\Store\StoreInterface;
use Zend\Db\Adapter\Adapter;
use Zend\Db\Sql\Select;
use Soluble\FlexStore\Source\Zend\SqlSource;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2013-10-14 at 18:08:25.
 */
class ResultSetTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var ResultSet
     */
    protected $resultset;

    /**
     * @var StoreInterface
     */
    protected $store;

    /**
     * @var Adapter
     */
    protected $adapter;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->adapter = \SolubleTestFactories::getDbAdapter();
        $select = new Select();
        $select->from('product_brand');

        $this->store = $this->getStore($select);

        $this->resultset = $this->store->getData();
    }

    /**
     * @param Select|null $select
     *
     * @return FlexStore
     */
    protected function getStore(Select $select = null)
    {
        $store = new FlexStore(new SqlSource($this->adapter, $select));

        return $store;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers \Soluble\FlexStore\ResultSet\AbstractResultSet::toArray
     */
    public function testGetArray()
    {
        $select = new \Zend\Db\Sql\Select();
        $select->from('product_brand');

        $store = $this->getStore($select);

        $resultset = $this->store->getData();
        $arr = $resultset->toArray();
        $this->assertInternalType('array', $arr);
    }

    public function testResultSetThrowsRuntimeException()
    {
        $this->setExpectedException('Soluble\FlexStore\ResultSet\Exception\RuntimeException');
        $adapter = \SolubleTestFactories::getDbAdapter();
        $select = new \Zend\Db\Sql\Select();
        $select->from('product_brand')->limit(10);
        $sql = new \Zend\Db\Sql\Sql($adapter);
        $sql_string = $sql->getSqlStringForSqlObject($select);
        $r = $adapter->query($sql_string, \Zend\Db\Adapter\Adapter::QUERY_MODE_EXECUTE);

        $rs = new ResultSet($r);
        $rs->getColumnModel();
    }

    public function testGetSource()
    {
        $select = new \Zend\Db\Sql\Select();
        $select->from('product_brand')->limit(1);

        $store = $this->getStore($select);
        $resultset = $store->getData();
        $this->assertInstanceOf('Soluble\FlexStore\Source\AbstractSource', $resultset->getSource());
    }

    public function testGetFieldCount()
    {
        $select = new \Zend\Db\Sql\Select();
        $select->from('product_brand')->limit(1)->columns(['reference']);
        $store = $this->getStore($select);
        $resultset = $store->getData();
        $this->assertEquals(1, $resultset->getFieldCount());

        $select = new \Zend\Db\Sql\Select();
        $select->from('product_brand')->limit(1)->columns(['reference', 'brand_id']);

        $store = $this->getStore($select);
        $resultset = $store->getData();
        $this->assertEquals(2, $resultset->getFieldCount());

        $select = new \Zend\Db\Sql\Select();
        $select->from('product_brand')->limit(1);

        $store = $this->getStore($select);
        $resultset = $store->getData();
        $this->assertEquals(14, $resultset->getFieldCount());
    }

    public function testGetTotal()
    {
        // With limit in the rquery
        $select = new \Zend\Db\Sql\Select();
        $select->from('product_brand')->limit(10)->columns(['reference']);

        $store = $this->getStore($select);
        //$options = new \Soluble\FlexStore\Options();
        //$options->setLimit(10);
        $resultset = $store->getData();
        $total = $resultset->getTotalRows();

        $this->assertEquals(10, $total);
        $this->assertEquals(10, count($resultset));
        $this->assertEquals(10, $resultset->count());

        // With no limit
        $select = new \Zend\Db\Sql\Select();
        $select->from('product_brand')->columns(['reference']);

        $store = $this->getStore($select);
        $options = new \Soluble\FlexStore\Options();
        $options->setLimit(10);
        $resultset = $store->getSource()->getData($options);
        $total = $resultset->getTotalRows();

        $this->assertEquals(93, $total);
        $this->assertEquals(10, count($resultset));
    }

    /**
     * @covers \Soluble\FlexStore\ResultSet\ResultSet::getPaginator
     */
    public function testGetPaginatorThrowsInvalidUsageException()
    {
        $this->setExpectedException('Soluble\FlexStore\Exception\InvalidUsageException');
        $paginator = $this->resultset->getPaginator();
        $this->assertInstanceOf('Zend\Paginator\Paginator', $paginator);
    }

    /**
     * @covers \Soluble\FlexStore\ResultSet\ResultSet::getPaginator
     */
    public function testGetPaginator()
    {
        $select = new \Zend\Db\Sql\Select();
        $select->from('product_brand');

        $store = $this->getStore($select);
        $source = $store->getSource();
        $source->getOptions()->setLimit(10, 0);
        $resultset = $source->getData();
        $paginator = $resultset->getPaginator();

        $this->assertInstanceOf('Soluble\FlexStore\Helper\Paginator', $paginator);

        $pages = $paginator->getPages();

        $this->assertEquals(10, $pages->itemCountPerPage);
        $this->assertEquals(1, $pages->first);
        $this->assertEquals(1, $pages->current);
    }
}
