<?php

/*
 * soluble-flexstore library
 *
 * @author    Vanvelthem Sébastien
 * @link      https://github.com/belgattitude/soluble-flexstore
 * @copyright Copyright (c) 2016-2017 Vanvelthem Sébastien
 * @license   MIT License https://github.com/belgattitude/soluble-flexstore/blob/master/LICENSE.md
 *
 */

namespace SolubleTest\FlexStore\Column\Type;

use PHPUnit\Framework\TestCase;
use Soluble\FlexStore\Column\Type\MetadataMapper;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2014-10-17 at 12:02:01.
 */
class MetadataMapperTest extends TestCase
{
    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    public function testGetColumnTypeByMetadataType()
    {
        $supported = \Soluble\Datatype\Column\Type::getSupportedTypes();
        $mapper = new MetadataMapper();
        foreach ($supported as $md_type) {
            $type = $mapper->getColumnTypeByMetadataType($md_type);
            $this->assertInstanceOf('Soluble\FlexStore\Column\Type\AbstractType', $type);
            $this->assertInternalType('string', $type->getName());
            $this->assertTrue(\Soluble\FlexStore\Column\ColumnType::isSupported($type->getName()));
        }
    }

    public function testGetColumnTypeByMetadataTypeThrowsInvalidArgumentException()
    {
        $this->expectException('Soluble\FlexStore\Column\Exception\InvalidArgumentException');
        $mapper = new MetadataMapper();
        $mapper->getColumnTypeByMetadataType('invalid_type');
    }
}
