<?php

namespace SolubleTest\FlexStore\Options;

use Soluble\FlexStore\Options\HydrationOptions;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2014-10-08 at 16:06:20.
 */
class HydrationOptionsTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var HydrationOptions
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new HydrationOptions();
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    public function testAll()
    {
        $ho = $this->object;
        $this->assertTrue($ho->isColumnExclusionEnabled());
        $this->assertTrue($ho->isRenderersEnabled());
        $this->assertTrue($ho->isFormattersEnabled());

        $ho->disableColumnExclusion();
        $ho->disableFormatters();
        $ho->disableRenderers();

        $this->assertFalse($ho->isColumnExclusionEnabled());
        $this->assertFalse($ho->isRenderersEnabled());
        $this->assertFalse($ho->isFormattersEnabled());

        $ho->enableColumnExclusion();
        $ho->enableFormatters();
        $ho->enableRenderers();

        $this->assertTrue($ho->isColumnExclusionEnabled());
        $this->assertTrue($ho->isRenderersEnabled());
        $this->assertTrue($ho->isFormattersEnabled());
    }
}
