<?php

namespace SolubleTest\FlexStore\Column\Search;

use Soluble\FlexStore\Source\Zend\SqlSource;
use Zend\Db\Sql\Select;
use Soluble\FlexStore\Store;
use Soluble\FlexStore\Column\ColumnModel;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-04-10 at 15:15:20.
 */
class ResultTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var SqlSource
     */
    protected $source;

    /**
     *
     * @var \Zend\Db\Adapter\Adapter
     */
    protected $adapter;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->adapter = \SolubleTestFactories::getDbAdapter();
        $select = new \Zend\Db\Sql\Select();
        $select->from('user');
        $this->source = new SqlSource($this->adapter, $select);
        $this->columnModel = $this->source->getColumnModel();
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }


    public function testSearchResults()
    {
        $source = new SqlSource($this->adapter);
        $select = $source->select();
        $select->from(['p' => 'product']);

        $store = new Store($source);
        $cm = $store->getColumnModel();

        $results = $cm->search()->regexp('/created_at/');

        $this->assertInstanceOf('Soluble\FlexStore\Column\ColumnModel\Search\Result', $results);

        $results->setEditable(true);
        $this->assertTrue($cm->get('created_at')->isEditable());
        $results->setEditable(false);
        $this->assertFalse($cm->get('created_at')->isEditable());

        $results->setExcluded(true);
        $this->assertTrue($cm->get('created_at')->isExcluded());
        $results->setExcluded(false);
        $this->assertFalse($cm->get('created_at')->isExcluded());

        $results->setSortable(true);
        $this->assertTrue($cm->get('created_at')->isSortable());
        $results->setSortable(false);
        $this->assertFalse($cm->get('created_at')->isSortable());


        $results->setHidden(true);
        $this->assertTrue($cm->get('created_at')->isHidden());
        $results->setHidden(false);
        $this->assertFalse($cm->get('created_at')->isHidden());


        $results->setVirtual(true);
        $this->assertTrue($cm->get('created_at')->isVirtual());
        $results->setVirtual(false);
        $this->assertFalse($cm->get('created_at')->isVirtual());


        $results->setGroupable(true);
        $this->assertTrue($cm->get('created_at')->isGroupable());
        $results->setGroupable(false);
        $this->assertFalse($cm->get('created_at')->isGroupable());

        $results->setFilterable(true);
        $this->assertTrue($cm->get('created_at')->isFilterable());
        $results->setFilterable(false);
        $this->assertFalse($cm->get('created_at')->isFilterable());

        $results->setWidth(10);
        $this->assertEquals(10, $cm->get('created_at')->getWidth());

        $results->setHeader('header');
        $this->assertEquals('header', $cm->get('created_at')->getHeader());

        $results->setType('date');
        $this->assertEquals('date', $cm->get('created_at')->getType());
    }
}
