<?php

/*
 * soluble-flexstore library
 *
 * @author    Vanvelthem Sébastien
 * @link      https://github.com/belgattitude/soluble-flexstore
 * @copyright Copyright (c) 2016-2017 Vanvelthem Sébastien
 * @license   MIT License https://github.com/belgattitude/soluble-flexstore/blob/master/LICENSE.md
 *
 */

namespace SolubleTest\FlexStore\Formatter;

use PHPUnit\Framework\TestCase;
use Soluble\FlexStore\Formatter\NumberFormatter;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2014-10-08 at 16:41:06.
 */
class NumberFormatterTest extends TestCase
{
    /**
     * @var NumberFormatter
     */
    protected $nf;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->nf = new NumberFormatter();
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    public function testConstruct()
    {
        $params = [
            'locale' => 'zh_CN',
            'pattern' => '#,##0.###',
            'decimals' => 3
        ];
        $f = new NumberFormatter($params);
        $this->assertEquals('zh_CN', $f->getLocale());
        $this->assertEquals('#,##0.###', $f->getPattern());
        $this->assertEquals(3, $f->getDecimals());
    }

    public function testGetSet()
    {
        $f = $this->nf;
        $this->assertInternalType('string', $f->getLocale());
        $this->assertEquals($f->getLocale(), substr(\Locale::getDefault(), 0, 5));
        $this->assertNull($f->getPattern());
        $this->assertEquals(2, $f->getDecimals());

        $f->setDecimals(3);
        $f->setPattern('#,##0.###');
        $f->setLocale('zh_CN');

        $this->assertEquals('zh_CN', $f->getLocale());
        $this->assertEquals('#,##0.###', $f->getPattern());
        $this->assertEquals(3, $f->getDecimals());
    }

    public function testFormat()
    {
        $params = [
            'locale' => 'fr_FR',
            'pattern' => '#,##0.###',
            'decimals' => 3
        ];

        $f = new NumberFormatter($params);

        self::assertEquals('1 123,457', $f->format(1123.4567));
        self::assertEquals('-1 123,457', $f->format(-1123.4567));


        $f->setLocale('en_US');
        $this->assertEquals('1,123.457', $f->format(1123.4567));
        $this->assertEquals('-1,123.457', $f->format(-1123.4567));

        $params = [
            'locale' => 'fr_BE'
        ];
        $f = new NumberFormatter($params);
        $this->assertEquals('1 123,46', $f->format(1123.4567));

        $params = [
            'locale' => 'en_GB'
        ];
        $f = new NumberFormatter($params);
        $this->assertEquals('1,123.46', $f->format(1123.4567));
    }

    public function testConstructThrowsInvalidArgumentException()
    {
        $this->expectException('Soluble\FlexStore\Exception\InvalidArgumentException');
        $params = [
            'cool' => 0
        ];
        $f = new NumberFormatter($params);
    }

    public function testFormatThrowsRuntimeException2()
    {
        $this->expectException('Soluble\FlexStore\Exception\RuntimeException');
        $params = [
            'locale' => 'fr_FR',
            'decimals' => 3
        ];
        $f = new NumberFormatter($params);
        $f->format(['cool']);
    }

    public function testFormatThrowsRuntimeException3()
    {
        $this->expectException('Soluble\FlexStore\Exception\RuntimeException');
        $params = [
            'locale' => 'fr_FR',
            'decimals' => 3
        ];
        $f = new NumberFormatter($params);
        $a = $f->format('not a number');
    }
}
