<?php

/*
 * soluble-flexstore library
 *
 * @author    Vanvelthem Sébastien
 * @link      https://github.com/belgattitude/soluble-flexstore
 * @copyright Copyright (c) 2016-2017 Vanvelthem Sébastien
 * @license   MIT License https://github.com/belgattitude/soluble-flexstore/blob/master/LICENSE.md
 *
 */

namespace SolubleTest\FlexStore;

use PHPUnit\Framework\TestCase;
use Soluble\FlexStore\Formatter;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2014-10-09 at 12:38:36.
 */
class FormatterTest extends TestCase
{
    public function testCreate()
    {
        $c = Formatter::create(Formatter::FORMATTER_CURRENCY);
        $this->assertInstanceOf('Soluble\FlexStore\Formatter\FormatterInterface', $c);
        $this->assertInstanceOf('Soluble\FlexStore\Formatter\FormatterNumberInterface', $c);
        $this->assertInstanceOf('Soluble\FlexStore\Formatter\CurrencyFormatter', $c);
        $this->assertInstanceOf('Soluble\FlexStore\Formatter\NumberFormatter', $c);

        $u = Formatter::create(Formatter::FORMATTER_UNIT);
        $this->assertInstanceOf('Soluble\FlexStore\Formatter\FormatterInterface', $u);
        $this->assertInstanceOf('Soluble\FlexStore\Formatter\FormatterNumberInterface', $u);
        $this->assertInstanceOf('Soluble\FlexStore\Formatter\UnitFormatter', $u);
        $this->assertInstanceOf('Soluble\FlexStore\Formatter\NumberFormatter', $u);

        $n = Formatter::create(Formatter::FORMATTER_NUMBER);
        $this->assertInstanceOf('Soluble\FlexStore\Formatter\FormatterInterface', $n);
        $this->assertInstanceOf('Soluble\FlexStore\Formatter\FormatterNumberInterface', $n);
        $this->assertInstanceOf('Soluble\FlexStore\Formatter\NumberFormatter', $n);
    }

    public function testCreateThrowsInvalidArgumentException()
    {
        $this->expectException('Soluble\FlexStore\Exception\InvalidArgumentException');
        $n = Formatter::create('cool');
    }

    public function testGetSupported()
    {
        $su = Formatter::getSupported();
        $this->assertInternalType('array', $su);
    }
}
