<?php

/*
 * soluble-flexstore library
 *
 * @author    Vanvelthem Sébastien
 * @link      https://github.com/belgattitude/soluble-flexstore
 * @copyright Copyright (c) 2016-2017 Vanvelthem Sébastien
 * @license   MIT License https://github.com/belgattitude/soluble-flexstore/blob/master/LICENSE.md
 *
 */

namespace SolubleTest\FlexStore\Options;

use PHPUnit\Framework\TestCase;
use Soluble\FlexStore\Options\HydrationOptions;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2014-10-08 at 16:06:20.
 */
class HydrationOptionsTest extends TestCase
{
    /**
     * @var HydrationOptions
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new HydrationOptions();
    }

    public function testAll()
    {
        $ho = $this->object;
        $this->assertTrue($ho->isColumnExclusionEnabled());
        $this->assertTrue($ho->isRenderersEnabled());
        $this->assertTrue($ho->isFormattersEnabled());

        $ho->disableColumnExclusion();
        $ho->disableFormatters();
        $ho->disableRenderers();

        $this->assertFalse($ho->isColumnExclusionEnabled());
        $this->assertFalse($ho->isRenderersEnabled());
        $this->assertFalse($ho->isFormattersEnabled());

        $ho->enableColumnExclusion();
        $ho->enableFormatters();
        $ho->enableRenderers();

        $this->assertTrue($ho->isColumnExclusionEnabled());
        $this->assertTrue($ho->isRenderersEnabled());
        $this->assertTrue($ho->isFormattersEnabled());
    }
}
